import 'package:flutter/material.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedIcon1024x1024FullWidget17.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedGroup6Widget4.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedGroup5Widget3.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedHomeIndicatorWidget18.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedEditeditWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedUploadfromphoneWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedLine18Widget2.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedGroup1523Widget1.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedCoverArtWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedGroup2Widget2.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedStatusBarWidget10.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedIconDarkChevronWidget8.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedGroup1483Widget2.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedTitleWidget11.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilemycontentwidget2/generated/GeneratedGroup1524Widget5.dart';

/* Frame Profile- My content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileMycontentWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: 34.0,
                child: GeneratedHomeIndicatorWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19466666666666665;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4026666666666667,
                        y: constraints.maxHeight * 0.06280788177339902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIcon1024x1024FullWidget17(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 335.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEditeditWidget4(),
              ),
              Positioned(
                left: 87.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedGroup2Widget2(),
              ),
              Positioned(
                left: 12.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 11.9765625,
                height: 20.7890625,
                child: GeneratedIconDarkChevronWidget8(),
              ),
              Positioned(
                left: 36.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 52.0,
                child: GeneratedGroup5Widget3(),
              ),
              Positioned(
                left: 1.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine18Widget2(),
              ),
              Positioned(
                left: 97.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 41.0,
                child: GeneratedGroup6Widget4(),
              ),
              Positioned(
                left: 150.0,
                top: null,
                right: 140.0,
                bottom: 442.0,
                width: null,
                height: 46.0,
                child: GeneratedTitleWidget11(),
              ),
              Positioned(
                left: 10.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 227.0,
                child: GeneratedGroup1483Widget2(),
              ),
              Positioned(
                left: 3.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 671.0,
                child: GeneratedGroup1523Widget1(),
              ),
              Positioned(
                left: 34.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 24.0,
                child: GeneratedCoverArtWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 24.0,
                child: GeneratedUploadfromphoneWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 52.0,
                child: GeneratedGroup1524Widget5(),
              )
            ]),
      ),
    ));
  }
}
