import 'package:flutter/material.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedEmailAddressWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedFrame1452Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedLine26Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedUserNameWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedLine27Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedLine25Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedLine24Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedEmailAddressWidget1.dart';
import 'package:flutterapp/fig2flutterapp/generatedsignupsigninpagewidget1/generated/GeneratedIcon1024x1024FullWidget2.dart';

/* Frame Sign Up/Sign In page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpSignInpageWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 52.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 1.0,
                child: GeneratedLine24Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 1.0,
                child: GeneratedLine25Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 1.0,
                child: GeneratedLine26Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 417,
                right: null,
                bottom: null,
                width: 308.0,
                height: 1.0,
                child: TransformHelper.translate(
                    x: -0.50, y: 11.50, z: 0, child: GeneratedLine27Widget()),
              ),
              Positioned(
                left: 17.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 24.0,
                child: GeneratedEmailAddressWidget(),
              ),

              Positioned(
                left: 32.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 24.0,
                child: GeneratedSignUpWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 24.0,
                child: GeneratedUserNameWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 27.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 24.0,
                child: GeneratedConfirmPasswordWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.296;

                  final double height =
                      constraints.maxHeight * 0.09236453201970443;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.352,
                        y: constraints.maxHeight * 0.04433497536945813,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIcon1024x1024FullWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 277.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 2.0,
                child: GeneratedFrame1452Widget(),
              )
            ]),
      ),
    ));
  }
}
