import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fig2flutterapp/generatedmessagingzachwidget/generated/GeneratedIconDarkChevronWidget5.dart';
import 'package:flutterapp/fig2flutterapp/generatedmessagingzachwidget/generated/GeneratedStatusBarWidget7.dart';
import 'package:flutterapp/fig2flutterapp/generatedmessagingzachwidget/generated/GeneratedAvatarWidget32.dart';
import 'package:flutterapp/fig2flutterapp/generatedmessagingzachwidget/generated/GeneratedSendyourfirstmessWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedmessagingzachwidget/generated/GeneratedHomeIndicatorWidget14.dart';
import 'package:flutterapp/fig2flutterapp/generatedmessagingzachwidget/generated/GeneratedMessageBarWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedmessagingzachwidget/generated/GeneratedNavigationBarLargeWidget.dart';

/* Frame Messaging- Zach
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessagingZachWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 813.0,
                child: GeneratedNavigationBarLargeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: 34.0,
                child: GeneratedHomeIndicatorWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.05541871921182266;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.5320197044334976,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMessageBarWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 79.0,
                top: 130.0,
                right: 78.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedSendyourfirstmessWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 11.9765625,
                height: 20.7890625,
                child: GeneratedIconDarkChevronWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13333333333333333;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.432,
                        y: constraints.maxHeight * 0.054187192118226604,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAvatarWidget32(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
