import 'package:flutter/material.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedLabelTitleWidget3.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedSongWidget2.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedGroup1486Widget3.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedLabelTitleWidget5.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedSongWidget4.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedGroup1537Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedGroup1529Widget2.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedHomeIndicatorWidget20.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedEllipse3Widget8.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedStatusBarWidget11.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedLabelTitleWidget4.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedSongWidget3.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedIconDarkChevronWidget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedZachFriedmanWidget.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedGroup1530Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedGroup1524Widget6.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedGroup2Widget3.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofileotherusercontentwidget/generated/GeneratedDirectionWidget6.dart';

/* Frame Profile- Other user content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileOtherusercontentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 376.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: 34.0,
                child: GeneratedHomeIndicatorWidget20(),
              ),
              Positioned(
                left: 37.0,
                top: null,
                right: null,
                bottom: null,
                width: 62.0,
                height: 62.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 333.00,
                    z: 0,
                    child: GeneratedGroup1486Widget3()),
              ),
              Positioned(
                left: 55.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 37.5,
                child: GeneratedGroup1530Widget(),
              ),
              Positioned(
                left: 182.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 37.5,
                child: GeneratedGroup1524Widget6(),
              ),
              Positioned(
                left: 289.0,
                top: null,
                right: null,
                bottom: null,
                width: 62.0,
                height: 62.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 330.00,
                    z: 0,
                    child: GeneratedEllipse3Widget8()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06382978723404255;

                  final double height =
                      constraints.maxHeight * 0.029556650246305417;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8590425531914894,
                        y: constraints.maxHeight * 0.8854679802955665,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSongWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 12.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 11.9765625,
                height: 20.7890625,
                child: GeneratedIconDarkChevronWidget9(),
              ),
              Positioned(
                left: 2.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 278.0,
                child: GeneratedGroup1537Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 59.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 100.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.26595744680851063;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.38563829787234044,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedGroup2Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 73.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 24.0,
                child: GeneratedZachFriedmanWidget(),
              ),
              Positioned(
                left: 355.20703125,
                top: 61.0,
                right: null,
                bottom: null,
                width: 26.20689582824707,
                height: 24.27597999572754,
                child: GeneratedDirectionWidget6(),
              ),
              Positioned(
                left: 94.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 192.0,
                child: GeneratedGroup1529Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06382978723404255;

                  final double height =
                      constraints.maxHeight * 0.029556650246305417;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8351063829787234,
                        y: constraints.maxHeight * 0.31157635467980294,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSongWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13297872340425532;

                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1356382978723404,
                        y: constraints.maxHeight * 0.3017241379310345,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSongWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 57.0,
                top: null,
                right: null,
                bottom: null,
                width: 36.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -91.50,
                    z: 0,
                    child: GeneratedLabelTitleWidget3()),
              ),
              Positioned(
                left: 178.0,
                top: null,
                right: null,
                bottom: null,
                width: 36.0,
                height: 20.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -95.00,
                    z: 0,
                    child: GeneratedLabelTitleWidget4()),
              ),
              Positioned(
                left: 292.0,
                top: null,
                right: null,
                bottom: null,
                width: 41.0,
                height: 20.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -95.00,
                    z: 0,
                    child: GeneratedLabelTitleWidget5()),
              )
            ]),
      ),
    ));
  }
}
