import 'package:flutter/material.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedGroup1531Widget.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedTitleWidget21.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedIconDarkChevronWidget13.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedSongWidget7.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedStatusBarWidget15.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedAvatarWidget35.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedIntersectWidget52.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedGroup1539Widget.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedStartTimeWidget.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedGroup1524Widget11.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget5/generated/GeneratedIcon1024x1024FullWidget21.dart';

/* Frame Dashboard- Zach
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardZachWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: null,
                  width: null,
                  height: 44.0,
                  child: GeneratedStatusBarWidget15(),
                ),
                Positioned(
                  left: 21.0,
                  top: 147.0,
                  right: null,
                  bottom: null,
                  width: 326.0,
                  height: 48.0,
                  child: GeneratedIntersectWidget52(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width = constraints.maxWidth * 0.072;

                    final double height =
                        constraints.maxHeight * 0.0332512315270936;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.07466666666666667,
                          y: constraints.maxHeight * 0.19950738916256158,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedAvatarWidget35(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.19466666666666665;

                    final double height =
                        constraints.maxHeight * 0.054187192118226604;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.4026666666666667,
                          y: constraints.maxHeight * 0.06280788177339902,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedIcon1024x1024FullWidget21(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 24.0,
                  top: 111.0,
                  right: null,
                  bottom: null,
                  width: 58.0,
                  height: 27.0,
                  child: GeneratedSongWidget7(),
                ),
                Positioned(
                  left: 24.0,
                  top: 230.0,
                  right: null,
                  bottom: null,
                  width: 106.0,
                  height: 24.0,
                  child: GeneratedStartTimeWidget(),
                ),
                Positioned(
                  left: 12.0,
                  top: 59.0,
                  right: null,
                  bottom: null,
                  width: 11.9765625,
                  height: 20.7890625,
                  child: GeneratedIconDarkChevronWidget13(),
                ),
                Positioned(
                  left: 60.0,
                  top: 172.0,
                  right: null,
                  bottom: null,
                  width: 180.0,
                  height: 15.0,
                  child: GeneratedRectangle3Widget(),
                ),
                Positioned(
                  left: 64.0,
                  top: null,
                  right: 121.0,
                  bottom: 626.0,
                  width: null,
                  height: 28.0,
                  child: GeneratedTitleWidget21(),
                ),
                Positioned(
                  left: 24.0,
                  top: 351.0,
                  right: null,
                  bottom: null,
                  width: 308.0,
                  height: 311.4472351074219,
                  child: GeneratedGroup1539Widget(),
                ),
                Positioned(
                  left: 36.0,
                  top: 696.0,
                  right: null,
                  bottom: null,
                  width: 308.0,
                  height: 52.0,
                  child: GeneratedGroup1524Widget11(),
                ),
                Positioned(
                  left: 21.0,
                  top: 266.0,
                  right: null,
                  bottom: null,
                  width: 326.0,
                  height: 42.0,
                  child: GeneratedGroup1531Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
