import 'package:flutter/material.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedIcon1024x1024FullWidget19.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedLabelTitleWidget9.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedGroup1505Widget.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedGroup1485Widget4.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedGroup1524Widget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedIconDarkChevronWidget12.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedStatusBarWidget14.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedGroup1526Widget1.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedLabelTitleWidget11.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedDirectionWidget7.dart';
import 'package:flutterapp/fig2flutterapp/generateddashboardzachwidget4/generated/GeneratedLabelTitleWidget10.dart';

/* Frame Dashboard- Zach
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardZachWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19466666666666665;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4026666666666667,
                        y: constraints.maxHeight * 0.06280788177339902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIcon1024x1024FullWidget19(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 12.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 11.9765625,
                height: 20.7890625,
                child: GeneratedIconDarkChevronWidget12(),
              ),
              Positioned(
                left: 355.2069091796875,
                top: 61.0,
                right: null,
                bottom: null,
                width: 26.20689582824707,
                height: 24.27597999572754,
                child: GeneratedDirectionWidget7(),
              ),
              Positioned(
                left: 19.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 540.0,
                child: GeneratedGroup1505Widget(),
              ),
              Positioned(
                left: 49.0,
                top: null,
                right: null,
                bottom: null,
                width: 37.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 363.50,
                    z: 0,
                    child: GeneratedLabelTitleWidget9()),
              ),
              Positioned(
                left: 52.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 37.5,
                child: GeneratedGroup1524Widget10(),
              ),
              Positioned(
                left: 171.0,
                top: null,
                right: null,
                bottom: null,
                width: 37.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 363.50,
                    z: 0,
                    child: GeneratedLabelTitleWidget10()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13333333333333333;

                  final double height =
                      constraints.maxHeight * 0.03711451450592192;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.43466666666666665,
                        y: constraints.maxHeight * 0.8805418719211823,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup1526Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 286.0,
                top: null,
                right: null,
                bottom: null,
                width: 37.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 363.50,
                    z: 0,
                    child: GeneratedLabelTitleWidget11()),
              ),
              Positioned(
                left: 267.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 56.0,
                child: GeneratedGroup1485Widget4(),
              )
            ]),
      ),
    ));
  }
}
