import 'package:flutter/material.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedGroup1538Widget1.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedGroup5Widget4.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedIconDarkChevronWidget10.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedStatusBarWidget12.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedHomeIndicatorWidget22.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedSongWidget5.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedGroup1536Widget.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedLabelTitleWidget6.dart';
import 'package:flutterapp/fig2flutterapp/generatedprofilelikedwidget/generated/GeneratedEditeditWidget6.dart';

/* Frame Profile- Liked
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileLikedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: 34.0,
                child: GeneratedHomeIndicatorWidget22(),
              ),
              Positioned(
                left: 12.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 11.9765625,
                height: 20.7890625,
                child: GeneratedIconDarkChevronWidget10(),
              ),
              Positioned(
                left: 33.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 52.0,
                child: GeneratedGroup5Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.064;

                  final double height =
                      constraints.maxHeight * 0.029556650246305417;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8373333333333334,
                        y: constraints.maxHeight * 0.31157635467980294,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSongWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 57.0,
                top: null,
                right: null,
                bottom: null,
                width: 36.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -91.50,
                    z: 0,
                    child: GeneratedLabelTitleWidget6()),
              ),
              Positioned(
                left: 51.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 334.0,
                child: GeneratedGroup1538Widget1(),
              ),
              Positioned(
                left: -4.547473508864641e-13,
                top: 395.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 151.0,
                child: GeneratedGroup1536Widget(),
              ),
              Positioned(
                left: 337.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEditeditWidget6(),
              )
            ]),
      ),
    ));
  }
}
